# Generated by Django 4.0.5 on 2022-06-20 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('title', models.CharField(max_length=200, null=True)),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('occupants_count', models.CharField(max_length=200, null=True)),
                ('bi0', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=200, null=True)),
                ('neighborhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='riverdale.neighborhood')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_prf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image', models.ImageField(upload_to='image/')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, null=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_img', to='riverdale.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200, null=True)),
                ('contacts', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('neighborhood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_id', to='riverdale.neighborhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bsn', to='riverdale.user')),
            ],
        ),
    ]
