# Generated by Django 4.0.5 on 2022-06-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riverdale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_id', to='riverdale.neighborhood'),
        ),
    ]
