# Generated by Django 4.0.5 on 2022-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdale', '0003_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='houses'),
        ),
    ]
