# Generated by Django 4.0.5 on 2022-06-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdale', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='house_no',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
