# Generated by Django 4.0.5 on 2022-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riverdale', '0009_rename_bi0_neighborhood_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='testimonials',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='testimonials1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='testimonials2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='testimonials3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
